num1 = int(input("Please enter a number between 0 and 100 inclusive: "))
num2 = int(input("Please enter a number between 0 and 100 inclusive: "))
num3 = int(input("Please enter a number between 0 and 100 inclusive: "))
print("The largest number you entered was: ", max(num1,num2,num3))
print("The smallest number you entered was: ", min(num1,num2,num3))
print("The average was", (num1+num2+num3) / 3)